# - To create a fresh environment (uses environment.yml by default):
#   $ conda env create
#
# - To update an existing environment to match:
#   $ conda env update --prune
#
name: toast
dependencies:
- alabaster=0.7.10=py36_0
- babel=2.4.0=py36_0
- colorama=0.3.7=py36_0
- coverage=4.4.1=py36_0
- docutils=0.13.1=py36_0
- flake8=3.3.0=py36_0
- imagesize=0.7.1=py36_0
- jinja2=2.9.6=py36_0
- markupsafe=0.23=py36_2
- mccabe=0.6.1=py36_0
- mkl=2017.0.1=0
- numpy=1.12.1=py36_0
- pandas=0.19.2=np112py36_1
- pip=9.0.1=py36_1
- py=1.4.33=py36_0
- pycodestyle=2.3.1=py36_0
- pyflakes=1.5.0=py36_0
- pygments=2.2.0=py36_0
- pyodbc=3.0.10=py36_1
- pytest=3.1.2=py36_0
- pytest-cov=2.3.1=py36_0
- python=3.6.1=0
- python-dateutil=2.6.0=py36_0
- pytz=2017.2=py36_0
- requests=2.14.2=py36_0
- scipy=0.19.0=np112py36_0
- setuptools=27.2.0=py36_1
- six=1.10.0=py36_0
- snowballstemmer=1.2.1=py36_0
- sphinx=1.6.2=py36_0
- sphinxcontrib=1.0=py36_0
- sphinxcontrib-websupport=1.0.1=py36_0
- sqlalchemy=1.1.9=py36_0
- vs2015_runtime=14.0.25123=0
- wheel=0.29.0=py36_0
- xlrd=1.0.0=py36_0
- xlsxwriter=0.9.6=py36_0
